[package]
name = "rubik_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
clap = "3.0.4"
rand = "0.8.4"
bincode = "1.3.3"
serde = "1.0.133"
crossbeam = "0.8.1"
